version: "3"
services:
  greenlitweb:
    image: "slaatipton/greenlit:rc-1"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:80"
    networks:
      - proxy
    depends_on:
      - greenlitsql
  greenlitsql:
    image: "microsoft/mssql-server-linux"
    volumes:
      - greenlitdata:/var/opt/mssql
    environment:
      SA_PASSWORD: "3oD48DAD"
      ACCEPT_EULA: "Y"

volumes:
  greenlitdata:

networks:
  proxy: