version: "3.3"
services:
  greenlitweb:
    image: "slaatipton/greenlit:rc-4"
    ports:
      - "8000:80"
    networks:
      - webnet
    labels:
      - "com.docker.ucp.mesh.http=external_route=http://greenlitauth.io,internal_port=80"
    depends_on:
      - greenlitsql
  greenlitsql:
    image: "microsoft/mssql-server-linux"
    networks:
      - webnet
    volumes:
      - greenlitdata:/var/opt/mssql
    environment:
      SA_PASSWORD: "3oD48DAD"
      ACCEPT_EULA: "Y"

volumes:
  greenlitdata:

networks:
  webnet:
    external:
      name: webnet