version: "3"
services:
    greenlitweb:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - sql.data
    sql.data:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "3oD48DAD"
            ACCEPT_EULA: "Y"