version: "3"
services:
  greenlitweb:
    image: "slaatipton/greenlit:rc-4"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8000:80"
    networks:
      - webnet
    depends_on:
      - greenlitsql
  greenlitsql:
    image: "microsoft/mssql-server-linux"
    ports:
      - "1437:1433"
    networks:
      - webnet
    volumes:
      - greenlitdata:/var/opt/mssql
    environment:
      SA_PASSWORD: "3oD48DAD"
      ACCEPT_EULA: "Y"

volumes:
  greenlitdata:

networks:
  webnet:
    external:
      name: webnet